### PR TITLE
Use query.Workmanager for cfilter queries

### PR DESCRIPTION
**Pull request by halseth**
Builds on #179

### CODE REVIEW

**Comment by wpaulino** [comment]
Needs a rebase!

**Comment by halseth** [comment]
Not yet ready for review.

**Comment by Chinwendu20** [comment]
I think we can close this now? Already achieved here? https://github.com/lightninglabs/neutrino/pull/273

**Comment by guggero** [comment]
Right. Replaced by https://github.com/lightninglabs/neutrino/pull/273.

**Pull request closed without merging**
